// Dicionário local de cartas Clash Royale (inglês -> português)
export const clashRoyaleCardTranslations: Record<string, string> = {
  Archer: "Arqueira",
  Archers: "Arqueiras",
  "Baby Dragon": "Bebê Dragão",
  Bandit: "Bandida",
  "Barbarian Barrel": "Barril de Bárbaro",
  Barbarians: "Bárbaros",
  Bats: "Morcegos",
  "Battle Healer": "Curadora de Batalha",
  "Battle Ram": "Ariete de Batalha",
  Bomber: "Bombardeiro",
  "Bomb Tower": "Torre de Bombas",
  Bowler: "Bola de Neve",
  Cannon: "Canhão",
  "Cannon Cart": "Carrinho de Canhão",
  "Dark Prince": "Príncipe das Trevas",
  "Electro Dragon": "Dragão Elétrico",
  "Electro Giant": "Gigante Elétrico",
  "Electro Spirit": "Espírito Elétrico",
  "Electro Wizard": "Mago Elétrico",
  "Elite Barbarians": "Bárbaros de Elite",
  Fireball: "Bola de Fogo",
  Firecracker: "Atiradora de Fogos",
  Fisherman: "Pescador",
  "Flying Machine": "Máquina Voadora",
  Freeze: "Congelamento",
  Giant: "Gigante",
  "Giant Skeleton": "Esqueleto Gigante",
  "Goblin Barrel": "Barril de Goblins",
  "Goblin Cage": "Gaiola de Goblin",
  "Goblin Gang": "Gangue de Goblins",
  "Goblin Giant": "Gigante Goblin",
  "Goblin Hut": "Cabana de Goblins",
  Goblins: "Goblins",
  Golem: "Golem",
  Graveyard: "Cemitério",
  Guards: "Guardiões",
  "Heal Spirit": "Espírito de Cura",
  "Hog Rider": "Corredor",
  Hunter: "Caçador",
  "Ice Golem": "Golem de Gelo",
  "Ice Spirit": "Espírito de Gelo",
  "Ice Wizard": "Mago de Gelo",
  "Inferno Dragon": "Dragão Infernal",
  "Inferno Tower": "Torre Inferno",
  Knight: "Cavaleiro",
  "Lava Hound": "Cão de Lava",
  Lightning: "Relâmpago",
  "Magic Archer": "Arqueiro Mágico",
  "Mega Minion": "Mega Servo",
  Miner: "Mineiro",
  "Mini P.E.K.K.A": "Mini P.E.K.K.A",
  Minions: "Servos",
  "Minion Horde": "Horda de Servos",
  Mirror: "Espelho",
  Musketeer: "Mosqueteira",
  "Night Witch": "Bruxa Sombria",
  "P.E.K.K.A": "P.E.K.K.A",
  Poison: "Veneno",
  Prince: "Príncipe",
  Princess: "Princesa",
  Rage: "Fúria",
  "Ram Rider": "Montadora de Carneiro",
  "Royal Delivery": "Entrega Real",
  "Royal Giant": "Gigante Real",
  "Royal Ghost": "Fantasma Real",
  "Royal Hogs": "Porcos Reais",
  "Royal Recruits": "Recrutas Reais",
  "Skeleton Army": "Exército de Esqueletos",
  "Skeleton Barrel": "Barril de Esqueletos",
  Skeletons: "Esqueletos",
  Sparky: "Sparky",
  "Spear Goblins": "Goblins Lanceiros",
  Tesla: "Tesla",
  "The Log": "O Tronco",
  "Three Musketeers": "Três Mosqueteiras",
  Tornado: "Tornado",
  Valkyrie: "Valquíria",
  "Wall Breakers": "Quebra-Muros",
  Witch: "Bruxa",
  Wizard: "Mago",
  "X-Bow": "X-Besta",
  Zap: "Zap",
};

export function translateCard(card: string): string {
  return clashRoyaleCardTranslations[card] || card;
}
